# [env]
# NODE_ENV = "development"

#[tools]
#node = "20"

# [tasks."docs:setup"]
# run = "npm install"

# [tasks."docs:dev"]
# run = "node docs/index.js"
# depends = ["docs:setup"]

[tasks."next:dev"]
run = "pnpm run dev"

[tasks."dev"]
run = "mise run next:dev"
